services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka
    ports:
      - "9092:9092"       # for internal Docker use
      - "29092:29092"     # for external host access
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,EXTERNAL://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    healthcheck:
      test: ["CMD", "bash", "-c", "kafka-topics --bootstrap-server localhost:9092 --list || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10

  emqx:
    image: emqx/emqx:5.8
    container_name: emqx
    ports:
      - "1883:1883"      # MQTT
      - "8083:8083"      # WebSocket
      - "18083:18083"    # Dashboard
    environment:
      - EMQX_LOADER__BOOT_DELAY=5s
      - EMQX_LOG__CONSOLE_HANDLER__LEVEL=debug
    volumes:
      - ./emqx_data:/opt/emqx/data
      - ./emqx_rules:/opt/emqx/etc/rules
      - ./emqx_log:/opt/emqx/log
      - ./emqx_rules/emqx_authz.conf:/opt/emqx/etc/emqx_authz.conf
      - ./emqx_conf/emqx.conf:/opt/emqx/etc/emqx.conf

  webhook-server:
    build:
      context: ./webhook_app
    depends_on:
      kafka:
        condition: service_healthy
    ports:
      - "4000:80"
    env_file:
      - .env
    environment:
      - MODULE_NAME=main
      - VARIABLE_NAME=app

  kafka-to-mqtt:
    build:
      context: ./kafka_to_mqtt
    depends_on:
      kafka:
        condition: service_healthy
      emqx:
        condition: service_started
    restart: unless-stopped
    env_file:
      - .env

